/**
 * Express router paths go here.
 */

export default {
	Base: '/api',
	Auth: {
		Base: '/auth',
		Login: '/login',
		Logout: '/logout',
		Signup: '/signup',
		VerifyEmail: '/verify-email',
		ResendEmail: '/resend-email',
		googleSignup: '/google-signup',
		googleLogin: '/google-login',
	},
	Users: {
		Base: '/users/user',
		Get: '/all',
		// Add: '/add',
		// Update: '/update',
		// Delete: '/delete/:id',
		UpdateDetails: '/update-details',
		uploadImage: '/upload-image',
		uploadComicsFile: '/upload-comics-file',
		getComicsFileUrl: '/get-comics-file-url',
		getUser: '/get-user',
		metrics: '/metrics',
	},
	Comics: {
		Base: '/comics',
		uploadComic: '/comic/upload',
		uploadToMarketPlace: '/comic/upload-to-market-place',
		allComic: '/all',
		userComics: '/comics/user',
		getComic: '/comic/:id/:episodeId',
		checkComic: '/check-comic',
		uploadComicAsPic: '/upload-comic-as-pic',
		uploadComicAsPdf: '/upload-comic-as-pdf',
		marketPlaceComics: '/market-place',
		makeAComment: '/make-a-comment',
		likeAComic: '/like-comic',
		likeAndUnlikeAcomment: '/like-and-unlike-a-comment',
		getNestedComments: '/get-nested-comments',
		getComments: '/get-comments/:id/:episodeId',
		getComicComments: '/get-comic-comments',
		getComicLikes: '/get-comic-likes',
		getComicSaved: '/get-comic-saves',
		getComicViews: '/get-comic-views',
		getComicFollowers: '/get-comic-followers',
		saveComic: '/save-comic',
		followComic: '/follow-comic',
		viewComic: '/view-comic',
	},
} as const;
