/**
 * Express router paths go here.
 */

import { get } from "http";

export default {
	Base: '/api',
	Auth: {
		Base: '/auth',
		Login: '/login',
		Logout: '/logout',
		Signup: '/signup',
		VerifyEmail: '/verify-email',
		ResendEmail: '/resend-email',
		googleSignup: '/google-signup',
		googleLogin: '/google-login',
	},
	Users: {
		Base: '/users/user',
		Get: '/all',
		// Add: '/add',
		// Update: '/update',
		// Delete: '/delete/:id',
		UpdateDetails: '/update-details',
		uploadImage: '/upload-image',
		uploadComicsFile: '/upload-comics-file',
		getComicsFileUrl: '/get-comics-file-url',
		getUser: '/get-user',
		metrics: '/metrics',
		getNotifications: '/get-notifications',
		readNotification: '/read-notification/:id',
	},
	Comics: {
		Base: '/comics',
		uploadComic: '/comic/upload',
		uploadToMarketPlace: '/comic/upload-to-market-place',
		allComic: '/all',
		userComics: '/comics/user',
		getComic: '/comic/:id/:episodeId',
		checkComic: '/check-comic',
		uploadComicAsPic: '/upload-comic-as-pic',
		uploadComicAsPdf: '/upload-comic-as-pdf',
		marketPlaceComics: '/market-place',
		makeAComment: '/make-a-comment',
		likeAComic: '/like-comic',
		likeAndUnlikeAcomment: '/like-and-unlike-a-comment',
		getNestedComments: '/get-nested-comments',
		getComments: '/get-comments/:id/:episodeId',
		getComicComments: '/get-comic-comments',
		getComicLikes: '/get-comic-likes',
		getComicSaved: '/get-comic-saves',
		getComicViews: '/get-comic-views',
		getComicFollowers: '/get-comic-followers',
		saveComic: '/save-comic',
		followComic: '/follow-comic',
		viewComic: '/view-comic',
		unapprovedComics: '/unapproved-comics',
	},

	Admins: {
		Base: '/admins',
		Login: '/login',
		Signup: '/signup',
		getProfile: '/profile',
		VerifyEmail: '/verify-email',
		ResendEmail: '/resend-email',
		approveComic: '/approve-comic',
		approveComicEpisode: '/approve-comic-episode',
		approveUser: '/approve-user',
		getUnapprovedComics: '/get-unapproved-comics',
		getUnapprovedEpisodes: '/get-unapproved-episodes',
		getUnapprovedUsers: '/get-unapproved-users',
		getAllUsers: '/get-all-users',
		getAllComics: '/get-all-comics',
		getAllEpisodes: '/get-all-episodes',
		getAllComments: '/get-all-comments',
		getAllLikes: '/get-all-likes',
		getAllSaves: '/get-all-saves',
		getAllViews: '/get-all-views',
		getAllFollowers: '/get-all-followers',
		getAllNotifications: '/get-all-notifications',
		getAllMetrics: '/get-all-metrics',
	},
} as const;
